name: Test bot installation script on different operating systems
on:
  push:
    branches: all
  pull_request:
    branches: [ main ]

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test bot script on ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run shell script
        run: |
          chmod +x install.sh
          ./install.sh       

